import { guests } from "@/lib/demo";
import { Brand } from "@/components/brand";
import { StatusDot } from "@/components/status-dot";

export default async function Room({ params }: { params: Promise<{roomId:string}> }) {
 const { roomId } = await params;
 return <main className="room-shell"><header className="room-top"><Brand/><div className="room-ident"><span>ROOM</span><b>{roomId.replaceAll("-"," ").toUpperCase()}</b></div><nav>{["ROOM","GUESTS","ROUTING","COMMS","DRAW","RECORD","OBS","DIAGNOSTICS"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</nav><div className="top-telemetry"><span><StatusDot state="ok"/> WEBRTC</span><span><StatusDot state="ok"/> OBS</span><b>01:42:18</b></div></header>
 <div className="room-body"><aside className="guest-rail"><div className="rail-title"><span>GUESTS</span><b>{guests.length}</b></div>{guests.map((g,i)=><button className={`guest-list-item ${i===0?"selected":""}`} key={g.name}><span className="avatar">{String(i+1).padStart(2,"0")}</span><span><b>{g.name}</b><small>{g.role}</small></span><StatusDot state={g.quality==="warning"?"warn":"ok"}/></button>)}<button className="invite-button">+ INVITE GUEST</button></aside>
 <section className="multiview"><div className="multiview-bar"><div><b>MULTIVIEW</b><span>4 SOURCES</span></div><div className="view-controls"><button>GRID</button><button>LIST</button><button className="active">ENGINEERING</button></div></div><div className="monitor-grid">{guests.map((g,i)=><article className="monitor" key={g.name}><div className="video-surface"><div className="video-noise"></div><div className="safe-label">INPUT {String(i+1).padStart(2,"0")}</div><div className="video-center"><span>{g.role}</span><b>{g.name}</b></div><div className="live-state"><StatusDot state={g.quality==="warning"?"warn":"ok"}/>{g.state}</div></div><div className="monitor-info"><div className="monitor-title"><div><strong>{g.name}</strong><small>{g.role}</small></div><span>{g.route}</span></div><div className="metric-grid"><span>FORMAT <b>{g.resolution} / {g.fps}</b></span><span>CODEC <b>{g.codec}</b></span><span>BITRATE <b>{g.bitrate}</b></span><span>RTT <b>{g.rtt}</b></span><span>LOSS <b className={g.quality==="warning"?"warning-text":""}>{g.loss}</b></span><span>JITTER <b>{g.jitter}</b></span></div><div className="audio-line"><span>MIC</span><div className="meter"><i style={{width:`${g.level}%`}}></i></div><b>-{Math.max(3,30-Math.round(g.level/3))} dB</b></div><div className="monitor-actions"><button>MUTE</button><button>SOLO</button><button className="talk">TALK</button><button>RETURN</button></div></div></article>)}</div></section>
 <aside className="inspector"><div className="inspector-head"><span>INSPECTOR</span><b>CASTER 01</b><small><StatusDot state="ok"/> Excellent connection</small></div><section><h3>RETURN FEED</h3><select defaultValue="PGM"><option>PGM</option><option>PVW</option><option>CLEAN</option><option>REPLAY</option></select><label><span>Programme audio</span><input type="checkbox" defaultChecked/></label><label><span>Talkback</span><input type="checkbox" defaultChecked/></label></section><section><h3>AUDIO</h3><div className="fader-line"><span>GAIN</span><input type="range" defaultValue="75"/><b>0.0 dB</b></div><label><span>Echo cancellation</span><b>ON</b></label><label><span>Noise suppression</span><b>ON</b></label><label><span>AGC</span><b>OFF</b></label></section><section><h3>NETWORK</h3><label><span>Transport</span><b>P2P</b></label><label><span>Candidate</span><b>UDP</b></label><label><span>RTT</span><b>23 ms</b></label><label><span>Packet loss</span><b>0.2%</b></label></section><button className="danger-button">REMOVE GUEST</button></aside></div>
 <footer className="comms-bar"><div><span className="kicker">COMMS</span><b><StatusDot state="ok"/> ALL CREW</b></div><button>CASTERS</button><button>PRODUCTION</button><button>OBSERVERS</button><button className="ptt">HOLD TO TALK</button><div className="clock"><span>LOCAL</span><b>--:--:--</b><small>LOCAL</small></div></footer></main>
}
