"use client";
import { useEffect, useRef, useState } from "react";
import { Brand } from "@/components/brand";
import { StatusDot } from "@/components/status-dot";

export default function JoinPage() {
 const videoRef = useRef<HTMLVideoElement>(null); const [status,setStatus]=useState("REQUEST ACCESS"); const [stream,setStream]=useState<MediaStream|null>(null);
 async function startMedia(){try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});setStream(s);if(videoRef.current)videoRef.current.srcObject=s;setStatus("DEVICES READY");}catch{setStatus("DEVICE ACCESS FAILED");}}
 useEffect(()=>()=>stream?.getTracks().forEach(t=>t.stop()),[stream]);
 return <main className="join-shell"><header><Brand/><span className="secure-label"><StatusDot state="ok"/> SECURE GUEST LINK</span></header><section className="join-card"><div className="join-copy"><span className="kicker">PRE-FLIGHT / CONTRIBUTOR</span><h1>Join production</h1><p>Check your camera, microphone and return audio before entering the producer waiting room.</p></div><div className="preview-box"><video ref={videoRef} autoPlay playsInline muted/><div className="preview-placeholder">{!stream&&<><b>CAMERA PREVIEW</b><span>Media remains on this device until you join.</span></>}</div></div><div className="form-grid"><label><span>DISPLAY NAME</span><input placeholder="Your name" defaultValue="Caster 01"/></label><label><span>CAMERA</span><select><option>Default camera</option></select></label><label><span>MICROPHONE</span><select><option>Default microphone</option></select></label><label><span>SPEAKER</span><select><option>System default</option></select></label></div><div className="readiness"><span><StatusDot state={stream?"ok":"idle"}/>Camera</span><span><StatusDot state={stream?"ok":"idle"}/>Microphone</span><span><StatusDot state="ok"/>Browser</span><span><StatusDot state="ok"/>Network</span></div><div className="join-actions"><button className="button ghost" onClick={startMedia}>{status}</button><button className="button primary" disabled={!stream}>ENTER WAITING ROOM</button></div><details><summary>ADVANCED MEDIA SETTINGS</summary><div className="advanced-grid"><label><span>QUALITY</span><select><option>BROADCAST — 1080p60</option><option>HIGH — 1080p30</option><option>STANDARD — 720p30</option></select></label><label className="toggle-row"><span>Echo cancellation</span><input type="checkbox" defaultChecked/></label><label className="toggle-row"><span>Noise suppression</span><input type="checkbox" defaultChecked/></label><label className="toggle-row"><span>Automatic gain control</span><input type="checkbox"/></label></div></details></section></main>
}
